TPE/config/routes.rb
Rails.application.routes.draw do
  get '/pages/acceuil', to: 'pages#acceuil'
  get '/pages/info', to: 'pages#info'
  get '/pages/plus', to: 'pages#plus'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

TPE/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

TPE/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def acceuil
  end

  def info
  end

  def plus
  end
end

TPE/app/helpers/application_helper.rb
module ApplicationHelper
end

TPE/app/helpers/pages_helper.rb
module PagesHelper
end

TPE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hello App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TPE/app/views/pages/acceuil.html.erb
<h1>Bienvenue sur notre app Rails Hello</h1>
<p>Ceci est la page d'accueil by Groupe 12 RTE3 | by IC3 INFOTEL 2025</p>
<ul>
  <li><%= link_to "Page Info", pages_info_path %></li>
  <li><%= link_to "Page Plus", pages_plus_path %></li>
</ul>

TPE/app/views/pages/info.html.erb
<h1>Info</h1>
<p>Ce projet montre comment Rails fonctionne .</p> 

TPE/app/views/pages/plus.html.erb
<h1>Page Plus</h1>
<p> 
Cette page est dédiée à des informations supplémentaires sur notre application Rails Hello. Vous pouvez y trouver des détails sur les fonctionnalités avancées, les intégrations et les mises à jour récentes.
Pour plus d'informations, n'hésitez pas à consulter notre documentation ou à nous contacter via le formulaire de contact disponible sur notre site. Nous sommes là pour vous aider à tirer le meilleur parti de notre application.
</p>